services:
  auth-service:
    build: ./auth-service
    environment:
      AUTH_SERVICE_DB_URI: jdbc:mysql://localhost/drive_auth
      AUTH_SERVICE_DB_USERNAME: root
      AUTH_SERVICE_DB_PASSWORD: root
      AUTH_SERVICE_GITHUB_CLIENT_ID: ${AUTH_SERVICE_GITHUB_CLIENT_ID}
      AUTH_SERVICE_GITHUB_CLIENT_SECRET: ${AUTH_SERVICE_GITHUB_CLIENT_SECRET}
      AUTH_SERVICE_GITHUB_REDIRECT_URI: ${AUTH_SERVICE_GITHUB_REDIRECT_URI}
      AUTH_SERVICE_CORS_ALLOWED_ORIGINS: ${AUTH_SERVICE_CORS_ALLOWED_ORIGINS}
    network_mode: host
    command:
      - "--server.port=${AUTH_SERVICE_PORT}"
      - "--server.ssl.key-store=/root/certs/localhost.p12"
    volumes:
      - /var/lib/jenkins/certs:/root/certs